config/routes.rb
Rails.application.routes.draw do
  root "companies#index"
  
  resources :sectors
  resources :communications
  
  resources :clients do
    resources :communications
  end

  resources :companies do
    resources :groups
  end
  
  resources :groups do
    resources :managers
  end

  resources :managers do
    resources :clients
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :group
  belongs_to :company
  has_many :clients

  has_many :clients

  validates :name, presence: true
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: %i[ show edit update destroy ]

  # GET /managers or /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1 or /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers or /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: "Manager was successfully created." }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1 or /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: "Manager was successfully updated." }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1 or /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: "Manager was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manager_params
      params.require(:manager).permit(:name, :email, :phone, :group_id, :company_id)
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= form_with model: @manager do |form| %>
  <% if manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
        <% manager.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.telephone_field :phone %>
  </div>

  <div class="field">
    <!-- once login implemented, make user company as the company -->
    <%= form.label :company_id %>
    <%= form.collection_select :company_id, Company.order(:name), :id, :name %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.collection_select :group_id, Group.order(:name), :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', "/groups/#{@manager.group_id}" %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Managers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.name %></td>
        <td><%= manager.email %></td>
        <td><%= manager.phone %></td>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager', new_manager_path %>

app/views/managers/new.html.erb
<h1>New Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Manager Info:
</h1>

<p>
  <strong>Name:</strong>
  <%= @manager.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @manager.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @manager.phone %>
</p>

<p>
  <strong>Clients:</strong>
  <ul>
    <% @manager.clients.each do |client| %>
    <li><%= client.first_name %> <%= client.last_name %> | <%= link_to 'Show', client_path %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'New Client', new_client_path %> |
<%= link_to 'Edit Manager', edit_manager_path(@manager) %> |
<%= link_to 'Back', "/groups/#{@manager.group_id}" %>