config/routes.rb
Rails.application.routes.draw do
  root "companies#index"
  
  resources :sectors
  resources :communications
  
  resources :clients do
    resources :communications
  end

  resources :companies do
    resources :groups
  end
  
  resources :groups do
    resources :managers
  end

  resources :managers do
    resources :clients
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :sector
  belongs_to :manager

  has_many :communications
end

app/models/client_type.rb
class ClientType < ApplicationRecord
  has_many :clients
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :email, :phone, :address, :company, :sector_id, :manager_id)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

    <div class="field">
    <%= form.label :sector_id, value ='Client Type' %>
    <%= form.collection_select :sector_id, Sector.order(:client_type), :id, :client_type %>
  </div>

  <div class="field">
    <%= form.label :manager_id %>
    <%= form.collection_select :manager_id, Manager.order(:name), :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Company</th>
      <th>Sector</th>
      <th>Manager</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.email %></td>
        <td><%= client.phone %></td>
        <td><%= client.address %></td>
        <td><%= client.company %></td>
        <td><%= client.sector_id %></td>
        <td><%= client.manager_id %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Client Info:
</h1>

<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Company:</strong>
  <%= @client.company %>
</p>

<p>
  <strong>Sector:</strong>
  <%= Sector.find(@client.sector_id).client_type %>
</p>

<p>
  <strong>Manager:</strong>
  <%= Manager.find(@client.manager_id).name %>
</p>

<p>
  <strong>Communications:</strong>
  <ul>
    <% @client.communications.each do |comm| %>
    <li><%= comm.created_at %> | <%= link_to 'Show', communication_path(comm.id) %>
                               | <%= link_to 'Delete', communication_path(comm.id), method: :delete, data: { confirm: "Are you sure?" } %> 
    <% end %>
  </ul>
</p>

<p>
  <strong>Add Communication:</strong>
  <%= render 'communications/form', communication: @communication %>
</p>

<%= link_to 'Edit Client', edit_client_path(@client) %> |
<%= link_to 'Back', "/managers/#{@client.manager_id}" %>